In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
train_full_df = pd.read_csv("/home/btech/nityanand.mathur/chexpert/CheXpert-v1.0-small/train.csv")

In [3]:
train_full_df.head()

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Lateral,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [4]:
train_full_df.columns

Index(['Path', 'Sex', 'Age', 'Frontal/Lateral', 'AP/PA', 'No Finding',
       'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity',
       'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis',
       'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture',
       'Support Devices'],
      dtype='object')

In [5]:
test_df = pd.read_csv('./CheXpert-v1.0-small/valid.csv')

In [6]:
test_df.head()

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/valid/patient64541/study1/...,Male,73,Frontal,AP,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CheXpert-v1.0-small/valid/patient64542/study1/...,Male,70,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,CheXpert-v1.0-small/valid/patient64542/study1/...,Male,70,Lateral,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,CheXpert-v1.0-small/valid/patient64543/study1/...,Male,85,Frontal,AP,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CheXpert-v1.0-small/valid/patient64544/study1/...,Female,42,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
#train_full_df['Path'] = train_full_df['Path'].str.replace(".jpg",".png")

/tmp/ipykernel_3311632/4106419961.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  train_full_df['Path'] = train_full_df['Path'].str.replace(".jpg",".png")

In [8]:
#test_df['Path'] = test_df['Path'].str.replace(".jpg",".png")

/tmp/ipykernel_3311632/3132916288.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  test_df['Path'] = test_df['Path'].str.replace(".jpg",".png")

In [9]:
test_df['Path'][0]

'CheXpert-v1.0-small/valid/patient64541/study1/view1_frontal.png'

To keep original val set as test, split train into 80/20

In [10]:
train_df, val_df = train_test_split(train_full_df, test_size=0.2, random_state=420, shuffle=True)

In [11]:
train_df.head()

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
147955,CheXpert-v1.0-small/train/patient35203/study28...,Male,66,Frontal,AP,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,1.0
163338,CheXpert-v1.0-small/train/patient38124/study5/...,Male,59,Frontal,AP,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN,1.0,1.0
69480,CheXpert-v1.0-small/train/patient16628/study1/...,Male,27,Frontal,PA,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,1.0,NaN
25205,CheXpert-v1.0-small/train/patient06161/study2/...,Male,61,Frontal,AP,NaN,NaN,1.0,1.0,NaN,NaN,0.0,NaN,-1.0,0.0,0.0,NaN,NaN,NaN
98537,CheXpert-v1.0-small/train/patient23744/study17...,Female,62,Lateral,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0

In [12]:
len(train_df)

178731

In [13]:
val_df.head()

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
67305,CheXpert-v1.0-small/train/patient16169/study2/...,Male,62,Frontal,AP,NaN,NaN,-1.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0
158250,CheXpert-v1.0-small/train/patient37045/study7/...,Female,69,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
51315,CheXpert-v1.0-small/train/patient12490/study12...,Male,51,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0
204270,CheXpert-v1.0-small/train/patient51556/study7/...,Female,68,Frontal,AP,NaN,NaN,NaN,1.0,NaN,-1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
71280,CheXpert-v1.0-small/train/patient17091/study1/...,Male,32,Frontal,PA,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN

In [14]:
len(val_df)

44683

In [15]:
count_frontal_train = train_df['Frontal/Lateral'].str.contains('Frontal', na=False).sum()
count_frontal_train

152672

In [16]:
count_lateral_train = train_df['Frontal/Lateral'].str.contains('Lateral', na=False).sum()
count_lateral_train

26059

In [17]:
def count(df):
    count_sum = df['Frontal/Lateral'].str.contains('Frontal', na=False).sum()
    return count_sum

In [18]:
print(count(val_df)) #lateral count

38355

In [19]:
print(count(val_df))#frontal count

38355

NaNs and -1s to ZEROS

In [20]:
def fill(df):
    return df.fillna(0)

In [21]:
train_df = fill(train_df)
val_df = fill(val_df)
test_df = fill(test_df)

In [22]:
train_df

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
147955,CheXpert-v1.0-small/train/patient35203/study28...,Male,66,Frontal,AP,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
163338,CheXpert-v1.0-small/train/patient38124/study5/...,Male,59,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0,0.0,1.0,0.0,1.0,1.0
69480,CheXpert-v1.0-small/train/patient16628/study1/...,Male,27,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25205,CheXpert-v1.0-small/train/patient06161/study2/...,Male,61,Frontal,AP,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
98537,CheXpert-v1.0-small/train/patient23744/study17...,Female,62,Lateral,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62239,CheXpert-v1.0-small/train/patient15019/study1/...,Female,85,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
152127,CheXpert-v1.0-small/train/patient35905/study3/...,Female,45,Frontal,AP,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
119174,CheXpert-v1.0-small/train/patient28559/study1/...,Female,57,Lateral,0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193608,CheXpert-v1.0-small/train/patient46927/study1/...,Male,46,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
142257,CheXpert-v1.0-small/train/patient34197/study4/...,Male,64,Lateral,0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [23]:
def zeroing(df):
    return df.replace(-1, 0)

In [24]:
train_df = zeroing(train_df)
val_df = zeroing(val_df)
test_df = zeroing(test_df)

In [25]:
train_df

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
147955,CheXpert-v1.0-small/train/patient35203/study28...,Male,66,Frontal,AP,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
163338,CheXpert-v1.0-small/train/patient38124/study5/...,Male,59,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
69480,CheXpert-v1.0-small/train/patient16628/study1/...,Male,27,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25205,CheXpert-v1.0-small/train/patient06161/study2/...,Male,61,Frontal,AP,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98537,CheXpert-v1.0-small/train/patient23744/study17...,Female,62,Lateral,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62239,CheXpert-v1.0-small/train/patient15019/study1/...,Female,85,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
152127,CheXpert-v1.0-small/train/patient35905/study3/...,Female,45,Frontal,AP,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
119174,CheXpert-v1.0-small/train/patient28559/study1/...,Female,57,Lateral,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193608,CheXpert-v1.0-small/train/patient46927/study1/...,Male,46,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
142257,CheXpert-v1.0-small/train/patient34197/study4/...,Male,64,Lateral,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [26]:
reordered_columns = [
    "Path",
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Pleural Effusion",
    "Pleural Other",
    "Pneumonia",
    "Pneumothorax",
    "Enlarged Cardiomediastinum",
    "Lung Opacity",
    "Lung Lesion",
    "Fracture",
    "Support Devices",
    "No Finding"
]

In [27]:
def reorder(df):
    return df[reordered_columns]

In [28]:
train_df = reorder(train_df)
val_df = reorder(val_df)
test_df = reorder(test_df)

In [29]:
train_df

,Path,Atelectasis,Cardiomegaly,Consolidation,Edema,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Enlarged Cardiomediastinum,Lung Opacity,Lung Lesion,Fracture,Support Devices,No Finding
147955,CheXpert-v1.0-small/train/patient35203/study28...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
163338,CheXpert-v1.0-small/train/patient38124/study5/...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
69480,CheXpert-v1.0-small/train/patient16628/study1/...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
25205,CheXpert-v1.0-small/train/patient06161/study2/...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
98537,CheXpert-v1.0-small/train/patient23744/study17...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62239,CheXpert-v1.0-small/train/patient15019/study1/...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
152127,CheXpert-v1.0-small/train/patient35905/study3/...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
119174,CheXpert-v1.0-small/train/patient28559/study1/...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193608,CheXpert-v1.0-small/train/patient46927/study1/...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
142257,CheXpert-v1.0-small/train/patient34197/study4/...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
def print_count(df):
    for i in range(1,len(df.columns)):
        print(df.columns[i], df[df.columns[i]].sum())

In [32]:
print_count(train_df)

Atelectasis 26795.0
Cardiomegaly 21671.0
Consolidation 11825.0
Edema 41987.0
Pleural Effusion 68928.0
Pleural Other 2801.0
Pneumonia 4818.0
Pneumothorax 15506.0
Enlarged Cardiomediastinum 8651.0
Lung Opacity 84302.0
Lung Lesion 7343.0
Fracture 7247.0
Support Devices 92742.0
No Finding 17794.0

In [33]:
print_count(val_df)

Atelectasis 6581.0
Cardiomegaly 5329.0
Consolidation 2958.0
Edema 10259.0
Pleural Effusion 17259.0
Pleural Other 722.0
Pneumonia 1221.0
Pneumothorax 3942.0
Enlarged Cardiomediastinum 2147.0
Lung Opacity 21279.0
Lung Lesion 1843.0
Fracture 1793.0
Support Devices 23259.0
No Finding 4587.0

In [34]:
print_count(test_df)

Atelectasis 80.0
Cardiomegaly 68.0
Consolidation 33.0
Edema 45.0
Pleural Effusion 67.0
Pleural Other 1.0
Pneumonia 8.0
Pneumothorax 8.0
Enlarged Cardiomediastinum 109.0
Lung Opacity 126.0
Lung Lesion 1.0
Fracture 0.0
Support Devices 107.0
No Finding 38.0

In [35]:
import os
os.getcwd()

'/home/btech/nityanand.mathur/chexpert'

In [37]:
train_df.to_csv("./labels/train_val_split_data/train_u-zeros.csv",index=False)

In [38]:
val_df.to_csv("./labels/train_val_split_data/val_u-zeros.csv",index=False)

In [39]:
test_df.to_csv("./labels/train_val_split_data/test_u-zeros.csv",index=False)